name: 'Github Build & Deploy Action'
description:
    'This action will auto deploy to target branch when it get triggered'
author: 'DuetDS <duetdesignsystem@lahitapiola.fi'
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'package'
    color: 'green'
